### ISSUE TITLE
ARCore 1.4.1 support?

### ISSUE THREAD

**Issue by aefox** [reigngt09/ARCore#2]
Hello,

I'm trying to follow the arcore training from udemy with the provided project files. I'm using ARCore 1.4.1 and Unity 2018.2 and I don't get the same "results" / "views" in unity as in the training. More specifically, I get an error saying the that andy's prefab is not initialized. Even more, the folder structure in the "Project" seems to be missing.

Thanks,
Fox

**Comment by suhas919** [comment]
Did you set the object in Inspector tab for andy prefab?

**Comment by aefox** [comment]
once I did that it worked. thanks a lot
